# Generated by Django 5.0.6 on 2025-09-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('payments', '0002_payout'),
    ]

    operations = [
    ]
