# Generated by Django 5.0.6 on 2025-09-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merge_0002_initial_0002_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
