# Generated by Django 5.0.6 on 2025-09-20 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("keycloak_user_id", models.CharField(max_length=255, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "avatar_url",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users_user",
        ),
        migrations.CreateModel(
            name="KeycloakUserSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keycloak_user_id", models.CharField(max_length=255, unique=True)),
                ("last_sync_at", models.DateTimeField()),
                ("sync_status", models.CharField(max_length=7)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("attributes_synced_json", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "keycloak_user_sync",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("location_json", models.JSONField(blank=True, null=True)),
                (
                    "login_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("success", models.BooleanField()),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "login_history",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activity_log",
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_type", models.CharField(max_length=8)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_addresses",
            },
        ),
        migrations.CreateModel(
            name="UserBusinessData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kyc_status", models.CharField(max_length=17)),
                ("kyc_documents_json", models.JSONField(blank=True, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "business_license",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("verification_notes", models.TextField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_business_data",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_email", models.BooleanField(default=True)),
                ("notification_sms", models.BooleanField(default=False)),
                ("notification_push", models.BooleanField(default=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("theme", models.CharField(default="light", max_length=5)),
                ("marketing_consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("pages_viewed", models.PositiveIntegerField()),
                ("time_spent_minutes", models.PositiveIntegerField()),
                ("products_viewed", models.PositiveIntegerField()),
                ("searches_made", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_behavior_analytics",
                "unique_together": {("user", "date")},
            },
        ),
    ]
