# Generated by Django 5.0.6 on 2025-09-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller_messages", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sellermessage",
            table="seller_message",
        ),
    ]
