# Generated by Django 5.0.6 on 2025-09-20 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
        ("shop", "0005_shopcategory_remove_shopdocument_shop_shop_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=100)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("report_data_json", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_reports",
            },
        ),
        migrations.CreateModel(
            name="PlatformMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_date", models.DateField(unique=True)),
                ("total_users", models.PositiveIntegerField()),
                ("active_users", models.PositiveIntegerField()),
                ("total_shops", models.PositiveIntegerField()),
                ("active_shops", models.PositiveIntegerField()),
                ("total_orders", models.PositiveIntegerField()),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platform_metrics",
            },
        ),
        migrations.AlterModelTable(
            name="report",
            table="reports_report",
        ),
        migrations.CreateModel(
            name="CustomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=255)),
                ("report_type", models.CharField(max_length=100)),
                ("filters_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_reports",
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=100)),
                ("report_data_json", models.JSONField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                    ),
                ),
            ],
            options={
                "db_table": "financial_reports",
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.CharField(max_length=7)),
                ("recipients_json", models.JSONField()),
                ("next_run_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.customreport",
                    ),
                ),
            ],
            options={
                "db_table": "report_schedules",
            },
        ),
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("total_orders", models.PositiveIntegerField()),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("new_customers", models.PositiveIntegerField()),
                ("returning_customers", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                    ),
                ),
            ],
            options={
                "db_table": "daily_sales_reports",
                "unique_together": {("report_date", "shop")},
            },
        ),
    ]
