# Generated by Django 5.0.6 on 2025-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
