# Generated by Django 5.0.6 on 2025-09-20 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_initial"),
        ("products", "0004_product_category"),
        ("shop", "0004_shop_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(max_length=9)),
                ("gateway_response_json", models.JSONField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "order_payments",
            },
        ),
        migrations.CreateModel(
            name="OrderRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=9)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_refunds",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "order_status_history",
            },
        ),
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tracking_url",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("last_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_tracking",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_type", models.CharField(max_length=8)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "db_table": "order_addresses",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("status", models.CharField(max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
    ]
